# Generated by Django 4.1.6 on 2023-05-18 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=10)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('scheduledAt', models.DateTimeField(blank=True, null=True)),
                ('maxSeatCapacity', models.IntegerField(max_length=5)),
                ('currentSeatCapacity', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeatBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.IntegerField(max_length=5)),
                ('flightId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_api.flights')),
                ('passengerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_api.passengers')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_api.paymentproviders')),
                ('seatBookingId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_api.seatbookings')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
